name: Issue Tracking
description: File a new issue
labels: ["enhancement", "needs-triage"]
body:

  - type: textarea
    id: feature-being-tested
    attributes:
      label: Feature Description
      description: Please describe the expected result
    validations:
      required: true

  - type: textarea
    id: bug-encountered
    attributes:
      label: Bug Encountered
      description: Please describe the issue you've been dealing with
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Feature Improvement Request
      description: Please describe the behavior you'd like to see. Explain how it will improve the application
    validations:
      required: true
